(core) Improved rtcheck messages when checking program points
Instead of getting the rtcheck message:

```
ERROR: (lns 2-5) main run-time check failure.
Requires in *pp_check*:
    $:('rtchecks_rt:rtc_inst'($:('term_typing:var'(a)),[a])).
```

it is displayed:

```
ERROR: (lns 2-5) main run-time check failure.
Requires in *pp_check*:
    var(a).
```

Src-commit: a653abb71265105919540f6f48e3138624678e6b